# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c790b267a815097d88574028fdb92c900f10ec84d9e4c4b917e75db663afe165688cce97daeac0937b3fc155f0a2d174d5f7da787b4813f7a831108b3f8e4e6

test:
  secret_key_base: f5501d8a9aea290e37eb105b76c46756388b6ddfcf404e039fe490ec13ef82b23b5743a9602e47075370542175c997b46d1d6bb35e500fbaf1c010a8c9bd5e8e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
